
INSERT INTO "T_CATALOGUE_ROLE" VALUES (1, 'USER');
INSERT INTO "T_CATALOGUE_ROLE" VALUES (2, 'ADMIN');
INSERT INTO "T_CATALOGUE_ROLE" VALUES (3, 'MASTER');

/* queries to poblate the interests table*/
INSERT INTO "T_CATALOGUE_INTEREST" VALUES (1, 'Tecnología');
INSERT INTO "T_CATALOGUE_INTEREST" VALUES (2, 'Inteligencia artificial');
INSERT INTO "T_CATALOGUE_INTEREST" VALUES (3, 'Literatura');
INSERT INTO "T_CATALOGUE_INTEREST" VALUES (4, 'Lingüística');
INSERT INTO "T_CATALOGUE_INTEREST" VALUES (5, 'Juegos');
INSERT INTO "T_CATALOGUE_INTEREST" VALUES (6, 'Animales');
INSERT INTO "T_CATALOGUE_INTEREST" VALUES (7, 'Astronomía');
INSERT INTO "T_CATALOGUE_INTEREST" VALUES (8, 'Moda');
INSERT INTO "T_CATALOGUE_INTEREST" VALUES (9, 'Economía');
INSERT INTO "T_CATALOGUE_INTEREST" VALUES (10, 'Entretenimiento');
INSERT INTO "T_CATALOGUE_INTEREST" VALUES (11, 'Cultura');
INSERT INTO "T_CATALOGUE_INTEREST" VALUES (12, 'Hogar');
INSERT INTO "T_CATALOGUE_INTEREST" VALUES (13, 'Vida cotidiana');
INSERT INTO "T_CATALOGUE_INTEREST" VALUES (14, 'Ciencia y educación');
INSERT INTO "T_CATALOGUE_INTEREST" VALUES (15, 'Comedia');
INSERT INTO "T_CATALOGUE_INTEREST" VALUES (16, 'Comida y bebidas');
INSERT INTO "T_CATALOGUE_INTEREST" VALUES (17, 'Vehículos');
INSERT INTO "T_CATALOGUE_INTEREST" VALUES (18, 'Anime');
INSERT INTO "T_CATALOGUE_INTEREST" VALUES (19, 'Música');
INSERT INTO "T_CATALOGUE_INTEREST" VALUES (20, 'Animales');
INSERT INTO "T_CATALOGUE_INTEREST" VALUES (21, 'Deportes');
INSERT INTO "T_CATALOGUE_INTEREST" VALUES (22, 'Salud');
INSERT INTO "T_CATALOGUE_INTEREST" VALUES (23, 'Belleza');
INSERT INTO "T_CATALOGUE_INTEREST" VALUES (24, 'Familia');
INSERT INTO "T_CATALOGUE_INTEREST" VALUES (25, 'Arte');
INSERT INTO "T_CATALOGUE_INTEREST" VALUES (26, 'Motivación');
INSERT INTO "T_CATALOGUE_INTEREST" VALUES (27, 'Viajes');
INSERT INTO "T_CATALOGUE_INTEREST" VALUES (28, 'DIY');